server:
  port: 8080
  servlet:
    context-path: /shopping/
    
spring: 
  liquibase:
    change-log: classpath:db/changelog/changelog.sql
  datasource: 
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: sa
    password: sa
  h2.console.enabled: true
  jpa:
    show-sql: true 
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: info
    liquibase: debug
